# Generated by Django 4.1.2 on 2022-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
